import { z } from 'zod';
import { projects } from './portfolio';
import { getProof } from './project-proof';
import { projectStrategies } from './project-strategy';
import { stateFarmCopy } from './state-farm-copy-update';
import { defaultStateFarmEvidence } from './state-farm-evidence-update';
import { maturityLevels, maturityContribution } from './state-farm-maturity';
const short=z.string().trim().min(1).max(400), text=z.string().trim().min(1).max(8000);
const mediaSrc=z.string().regex(/^\/(api\/portfolio-media\/[0-9a-f-]{36}|work\/[a-zA-Z0-9_.-]+)$/);
const section=z.enum(['maturity','evidence','research','strategy','decisions','impact']);
const strategy=z.object({context:text,comparisons:z.array(z.object({title:short,question:text})).min(1).max(8),opportunity:text,engagement:z.array(z.object({title:short,direction:text})).min(1).max(8),signals:z.array(short).min(1).max(10)}).strict();
const editableProject=z.object({slug:short,company:short,title:short,subtitle:text,role:short,domain:short,challenge:text,contribution:z.array(text).min(1).max(8),evidence:text,takeaway:text,decisions:z.array(z.object({title:short,text})).min(2).max(8)}).strict();
const caseDetails=z.object({timeframe:z.string().trim().max(400).optional(),assessmentDate:z.string().trim().max(400).optional(),researchObservation:z.string().trim().max(8000).optional(),designChange:z.string().trim().max(8000).optional(),researchArtifactSrc:z.union([z.literal(''),mediaSrc]).optional(),deliveryExample:z.string().trim().max(8000).optional()}).strict();
const study=z.object({caseDetails:caseDetails.optional(),project:editableProject,scope:text,collaboration:text,visualLabel:short,researchIntro:text,researchNote:text,outcomeNote:text,insights:z.array(text).min(1).max(8),choice:text,why:text,directional:text,strategy,evidence:z.array(z.object({id:short,title:short,status:z.enum(['Project summary','Artifact available','Placeholder']),summary:text,detail:text,src:z.string().regex(/^\/(work\/|api\/portfolio-media\/)[a-zA-Z0-9/_.-]+$/).optional()})).max(20),media:z.array(z.object({title:short,caption:z.string().max(2000),src:mediaSrc,type:z.enum(['image','video'])})).max(12),sectionOrder:z.array(section).min(5).max(6)}).strict();
export const contentSchema=z.object({stateFarmCopyVersion:z.literal(1).optional(),stateFarmEvidenceVersion:z.union([z.literal(1),z.literal(2)]).optional(),home:z.object({heroBadge:short,heroLines:z.array(short).length(4),heroDescription:text,workTitle:short,workDescription:text,aboutTitle:short,aboutParagraphs:z.array(text).length(2)}).strict(),projectOrder:z.array(short).length(4),studies:z.record(study),maturity:z.object({contribution:text,levels:z.array(z.object({level:z.number().int().min(1).max(3),name:short,principle:short,stage:short,summary:text,capabilities:z.array(short).min(1).max(6),product:text,engineering:text,customer:text,example:text,exampleResponse:text})).length(3)}).strict()}).strict().superRefine((value,ctx)=>{
 const slugs=projects.map(p=>p.slug);
 if(new Set(value.projectOrder).size!==4||value.projectOrder.some(s=>!slugs.includes(s))||Object.keys(value.studies).sort().join()!==[...slugs].sort().join())ctx.addIssue({code:'custom',message:'Keep the four existing projects.'});
 for(const slug of slugs){const s=value.studies[slug];if(!s)continue;const required=slug==='digital-assistance'?['maturity','evidence','research','strategy','decisions','impact']:['evidence','research','strategy','decisions','impact'];if(s.project.slug!==slug||[...s.sectionOrder].sort().join()!==required.sort().join())ctx.addIssue({code:'custom',message:'Keep each case-study section once.'});}
 if(value.maturity.levels.map(l=>l.level).join()!=='1,2,3')ctx.addIssue({code:'custom',message:'Keep maturity levels 1, 2, and 3.'});
});
export type PortfolioContent=z.infer<typeof contentSchema>;
export const sectionLabels:Record<string,string>={maturity:'AI Maturity Model',evidence:'Follow the evidence',research:'Research',strategy:'Competitive Intelligence + Engagement Strategy',decisions:'Design decisions',impact:'Outcomes & lessons'};
const collaboration:Record<string,string>={ 'digital-assistance':'Aligned Product and Engineering through shared conversation patterns, a Digital Assistance design kit, and the AI Maturity Model.', 'apple-intelligence':'Partnered with data scientists, ML engineers, and platform teams on interaction patterns and prototype validation.',upgather:'Worked with Engineering on consistency and change tracking across Figma, Storybook, and the repository.','design-systems':'Worked through implementation trade-offs with Engineering using working sessions, prototypes, and shared references.' };
export const defaultContent:PortfolioContent=contentSchema.parse({
 stateFarmCopyVersion:1,stateFarmEvidenceVersion:2,home:{heroBadge:'AI Product Design & Experience Strategy',heroLines:['Human insight.','AI strategy.','Product design.','Better products.'],heroDescription:'I turn complex systems into clear, useful products through human–AI interaction and hands-on design.',workTitle:'Complexity, made useful.',workDescription:'AI experiences, enterprise products, and systems built with Product and Engineering.',aboutTitle:'Strategy in mind.\nCraft in hand.',aboutParagraphs:['I’m Terry Germany, a senior and principal-level product design leader based in Carrollton, Texas. I bring 25+ years of experience across Apple, Cisco, State Farm, and Scoop News Group.','I connect human–AI interaction, research, and hands-on design with Product and Engineering—making complex systems clear, useful, and trusted.']},
 projectOrder:projects.map(p=>p.slug), studies:Object.fromEntries(projects.map(p=>{const proof=getProof(p.slug);return[p.slug,{project:{slug:p.slug,company:p.company,title:p.title,subtitle:p.subtitle,role:p.role,domain:p.domain,challenge:p.challenge,contribution:p.contribution,evidence:p.evidence,takeaway:p.takeaway,decisions:p.decisions},scope:proof.scope,collaboration:collaboration[p.slug],visualLabel:proof.visualLabel,researchIntro:p.slug==='apple-intelligence'?'UX research, usability testing, and prototype iteration supported the work. Internal findings remain private.':p.slug==='digital-assistance'?'Research focused on how customers recognize assistance, enter a conversation, and move through insurance tasks.':'The project notes identify these design questions; validated research findings are not supplied.',researchNote:p.slug==='digital-assistance'?'Entry-point, button, and interface variations were prepared for moderated research and A/B testing. Specific findings and post-test changes are not supplied.':'These points summarize the project account; they are not participant quotations or measured findings.',outcomeNote:'Quantitative launch results are not available in these project notes.',insights:proof.insights,choice:proof.choice,why:proof.why,directional:proof.directional,strategy:projectStrategies[p.slug],evidence:proof.evidence,media:proof.prototypes.filter(m=>m.src).map(m=>({title:m.title,caption:m.caption,src:m.src,type:m.type})),sectionOrder:[...(p.slug==='digital-assistance'?['maturity']:[]),'evidence','research','strategy','decisions','impact'],...(p.slug==='digital-assistance'?{...stateFarmCopy,evidence:defaultStateFarmEvidence}:{})}];})),maturity:{contribution:maturityContribution,levels:maturityLevels}
});
export function contentProjects(content:PortfolioContent){return content.projectOrder.map(slug=>({...projects.find(p=>p.slug===slug)!,...content.studies[slug].project}));}
