import { projects, type Project } from "./portfolio";
import { stateFarmMedia, type CaseMedia } from "./state-farm-media";
import { strategyEvidence } from "./project-strategy";
import { maturityEvidence } from "./state-farm-maturity";

export type Evidence = { id: string; title: string; status: "Project summary" | "Artifact available" | "Placeholder"; summary: string; detail: string; src?: string };
type Partner = { role: string; contribution: string; change: string };
export type Proof = { scope: string; visual: string; visualLabel: string; insights: string[]; options: { title: string; text: string }[]; choice: string; why: string; testing: string; system: { title: string; text: string }[]; partners: Partner[]; target: string; targetNote: string; directional: string; next: string; prototypes: CaseMedia[]; evidence: Evidence[]; beforeAfter?: [string,string] };

const pending = "Placeholder — add an approved artifact and its context. No findings or quotations are asserted here.";
const partner = (role: string, contribution: string, change: string): Partner => ({role, contribution, change});
const missingPartner = (role: string) => partner(role, "A specific account of this partnership has not been added yet.", "Add a concrete contribution, decision, and resulting change before treating this as evidence.");
const base: Record<string,Omit<Proof,"evidence">> = {
  "digital-assistance": {
    scope: "12+ customer journeys · 15+ cross-functional teams", visual: "/work/state-farm-assistant.png", visualLabel: "Conversational assistant prototype",
    insights: ["Assistance must work across shopping, service, registration, and claims.", "Task complexity informed the choice of mobile full-page and desktop surfaces.", "Recognition, clarity, and human handoff were central research questions."],
    options: [{title:"Full-page assistance",text:"Room for a focused journey. The documented direction for mobile; also explored for complex desktop tasks."},{title:"Desktop widget",text:"A compact entry point alongside the existing page. Explored as one desktop pattern."},{title:"Side panel",text:"Keep the task context visible while adding guidance. Explored as another desktop pattern."}],
    choice: "Match the surface to the task.", why: "The documented direction uses mobile full-page assistance and explores multiple desktop patterns around task complexity. A single surface was not prescribed for every journey.", testing: "Entry-point, button, and interface variations were developed for moderated research and A/B testing. Specific findings and post-test changes have not been added yet.",
    system: [{title:"Invite",text:"Make the assistance entry point recognizable and relevant to the customer's context."},{title:"Guide",text:"Use shared conversation patterns across widgets, side panels, and full-page experiences."},{title:"Hand off",text:"Explain what is happening and provide a path to human support."}],
    partners: [partner("Product","Connected experience strategy across 12+ journeys and implemented the AI Maturity Model with Product and Engineering.","A shared framework for progressing from Level 1 Assisted Automation through context-aware assistance to Level 3 Predictive AI Companion."), partner("Engineering","Contributed the Digital Assistance design kit and implemented the AI Maturity Model with Product and Engineering.","Connected the Level 1-to-Level 3 progression to customer experience and technical capability. Specific release details and engineering trade-offs are documented separately."),partner("Research","Directed research and entry-point/interface variations for moderated studies and A/B testing.","Research questions became tangible prototypes. Test findings and resulting changes are pending."),missingPartner("Data Science"),partner("Content","Contributed conversation patterns, contextual guidance, and explainability concepts.","A documented focus on clarity and human control. Content-team ownership details are pending."),partner("Leadership","Created executive prototypes and introduced the AI Maturity Model with Product and Engineering.","A shared language for the progression from rules-based assistance to context-aware and predictive experiences."),missingPartner("Operations")],
    target: "Up to 50%", targetNote: "Fewer actions in one workflow exploration. Design target; not a measured launch result.",directional: "A shared model for digital assistance across journeys and surfaces.",next:"Add approved research findings, the tested before-and-after flow, and measured results to show which decisions held up in use.",prototypes:[{title:"Conversational mobile assistant",caption:"Project prototype. Select to inspect the complete screen.",src:"/work/state-farm-assistant.png",type:"image"},...stateFarmMedia]
  },
  "apple-intelligence": {
    scope:"iOS · macOS · tvOS · web",visual:"/hero-media/violet.png",visualLabel:"Concept visual · not an Apple product screen",
    insights:["Intelligent capabilities need to fit familiar product behavior.","Accessibility and platform consistency informed interaction decisions.","Usability testing and prototype iteration supported interaction quality; internal findings remain private."],
    options:[{title:"Familiar product patterns",text:"The documented approach: interaction flows aligned with Human Interface Guidelines and accessibility principles."},{title:"Dedicated AI workspace",text:"Illustrative alternative for comparison: a separate destination could provide focus but introduce another interaction model."},{title:"Custom interface language",text:"Illustrative alternative for comparison: distinct controls could signal intelligence but require people to learn unfamiliar behavior."}],
    choice:"Start with the interaction people already understand.",why:"Translated intelligent system behavior into familiar product flows while supporting a common component foundation across teams.",testing:"Usability testing and prototype iteration are documented methods. Specific internal findings and implementation changes are not reproduced here.",
    system:[{title:"System behavior",text:"Work with data scientists and ML engineers to understand the intelligent capability."},{title:"Product interaction",text:"Translate behavior into understandable, accessible platform experiences."},{title:"Shared foundation",text:"Support reusable components and cross-team workflows through Sketch-to-Figma migration."}],
    partners:[partner("Product","Contributed experience architecture and UI/UX across intelligent product surfaces.","A common interaction direction across platforms; specific internal decisions remain private."),partner("Engineering","Partnered with ML engineers and platform teams on UI/UX and prototype validation.","Technical behavior informed product interaction. Proprietary implementation details are not shown."),partner("Research","Combined UX research with usability testing and prototype iteration.","Interaction quality and shared standards were refined; internal findings remain private."),partner("Data Science","Partnered with data scientists on intelligent product surfaces.","System behavior informed experience architecture. No model-specific claims are made here."),missingPartner("Content"),partner("Leadership","Contributed designer mentorship and a unified component foundation.","Supported shared design practices; no delivery or adoption metric is supplied."),missingPartner("Operations")],
    target:"Coherence",targetNote:"Design intent: familiar, accessible interactions across platforms. No numeric target is supplied.",directional:"Interaction patterns, reusable components, and prototype validation.",next:"Show approved, non-confidential examples of interaction reasoning and accessibility decisions when those materials can be shared.",prototypes:[{title:"Interaction study",caption:"Approved, non-confidential interaction example to be added. Proprietary Apple screens are not reproduced.",src:null,type:"image"},{title:"Prototype walkthrough",caption:"Add a shareable walkthrough or a clearly labeled recreation with permission.",src:null,type:"video"}]
  },
  upgather:{
    scope:"Event creation · operational workflows · design system",visual:"/work/editorial-ai.png",visualLabel:"Upgather editorial workflow exploration",
    insights:["Event work connects speakers, organizations, invitations, content, and publishing.","Guided creation and ongoing management need distinct starting points.","Draft states and contextual panels make operational work easier to navigate. These are design directions, not measured usability findings."],
    options:[{title:"Create a new layout",text:"Start a guided event setup with a new page layout."},{title:"Reuse a layout",text:"Use an existing layout as a starting point rather than rebuilding the page."},{title:"Save a draft",text:"Preserve unfinished setup and return to the operational workspace."}],
    choice:"Support all three paths within a clear creation flow.",why:"Separated guided event setup from ongoing management. New layouts, reusable layouts, and drafts address different starting conditions rather than competing for one winner.",testing:"The work is an ongoing design initiative. Test results and post-test changes have not been supplied; they should be added alongside an approved creator prototype.",
    system:[{title:"Create",text:"Give event setup a clear start, with reusable layouts and drafts."},{title:"Manage",text:"Use operational tables, AG Grid, and contextual panels for connected workflows."},{title:"Maintain",text:"Align Figma, Storybook, and repository changes with engineering. Automation remains an evolving workflow."}],
    partners:[partner("Product","Connected a North Star experience with hands-on enterprise platform flows.","Creation and ongoing operations were treated as distinct design contexts."),partner("Engineering","Worked on system consistency and change tracking across Figma, Storybook, and the repository.","A traceable design-to-code direction. Integration concepts and automation are not claimed as shipped."),missingPartner("Research"),missingPartner("Data Science"),partner("Content","Designed workflows spanning editorial content and publishing.","Reusable layouts and creation patterns are visible in supplied explorations; editorial-team feedback is pending."),partner("Leadership","Contributed cross-product direction alongside hands-on design.","A North Star connected to practical workflows. Specific leadership decisions are pending."),partner("Operations","Designed members, organizations, invitations, and confirmation workflows.","Tables, contextual panels, and drafts address ongoing operational work. Measured effects have not been added.")],
    target:"Clear next step",targetNote:"Design intent for event setup and operational work. A numeric success target has not been supplied.",directional:"Guided creation, reusable layouts, contextual panels, and shared system alignment.",next:"Validate creation and draft-recovery paths with operators, then add findings and delivery status beside each prototype.",prototypes:[{title:"Editorial workflow exploration",caption:"Supplied Upgather design exploration. Select to inspect the full sequence.",src:"/work/editorial-ai.png",type:"image"},{title:"Event journey map",caption:"Supplied event-flow diagram. Design exploration, not a measured production outcome.",src:"/work/event-flow.png",type:"image"},{title:"Event creator walkthrough",caption:"Add an approved walkthrough of new layouts, reuse, and drafts.",src:null,type:"video"}],beforeAfter:["The challenge: connected event and data tasks can obscure what to do next.","Designed direction: guided setup, reusable layouts, draft states, and contextual operational panels. Qualitative comparison; no before-and-after benchmark is supplied."]
  },
  "design-systems":{
    scope:"Components · behavior · handoff · change tracking",visual:"/hero-media/silver.png",visualLabel:"Concept visual · a shared system of parts",
    insights:["Component usefulness depends on shared understanding of behavior and constraints.","States, accessibility, content, and responsive behavior belong alongside visual specifications.","Documented changes and tracked work come before proposed automation."],
    options:[{title:"Behavior alongside visuals",text:"The documented approach: define states, accessibility, content, responsiveness, and handoff together."},{title:"Visual library first",text:"Illustrative alternative: prioritize appearance, then resolve behavior during implementation. This can leave decisions implicit."},{title:"Implementation first",text:"Illustrative alternative: let code lead, then align design later. This can make design intent harder to trace."}],
    choice:"Define behavior and engineer alongside design.",why:"Working sessions, prototypes, and shared references make constraints visible early while preserving room for product-specific choices.",testing:"Prototype reviews and implementation trade-offs are documented methods. A specific test, failed concept, and resulting component revision have not been supplied.",
    system:[{title:"Design intent",text:"Reusable Figma components plus documented interaction behavior."},{title:"Shared reference",text:"Prototype reviews and Storybook/repository workflows clarify trade-offs."},{title:"Traceable change",text:"Track changes before moving toward automation. Automatic Figma MCP syncing is not a deployed capability."}],
    partners:[partner("Product","Established repeatable standards with room for product-specific decisions.","A shared language for variations and constraints; product-specific outcomes are pending."),partner("Engineering","Worked through implementation trade-offs and prototype reviews.","Storybook and repository workflows became shared references for alignment."),missingPartner("Research"),missingPartner("Data Science"),partner("Content","Documented content expectations alongside component behavior.","Content became part of the handoff specification; specific content-team contributions are pending."),partner("Leadership","Contributed mentoring and cross-team design standards.","Supported repeatable practices. Adoption and delivery measurements have not been added."),missingPartner("Operations")],
    target:"Shared behavior",targetNote:"Design intent: consistent components and traceable changes. No numeric delivery target is supplied.",directional:"Reusable components, documented standards, implementation alignment, and mentoring.",next:"Add a real component revision from design intent through implementation, then document adoption, accessibility, and delivery evidence.",prototypes:[{title:"Component behavior study",caption:"Add an approved state matrix or responsive component example.",src:null,type:"image"},{title:"Design-to-code walkthrough",caption:"Add a walkthrough of a documented change, review, and implementation.",src:null,type:"video"}]
  }
};

function evidenceFor(p:Project, proof:Omit<Proof,"evidence">):Evidence[] {
 const research = p.slug === "digital-assistance" ? "Moderated research and A/B testing informed the research plan around assistance entry points, buttons, and interfaces. Findings are awaiting approved artifacts." : p.slug === "apple-intelligence" ? "UX research, usability testing, and prototype validation supported interaction work. Internal findings and research artifacts remain private." : "Research findings have not been added to this project. The current account describes design direction and methods.";
 return [
  {id:"research",title:"User research",status:p.tags.includes("Research")?"Project summary":"Placeholder",summary:p.tags.includes("Research")?"Research approach and validation methods.":"Research findings to be added.",detail:research},
  {id:"interviews",title:"Interview snippets",status:"Placeholder",summary:"Approved excerpts and context to be added.",detail:pending+" Include the participant context, date, and how the excerpt affected a decision."},
  {id:"whiteboards",title:"FigJam / whiteboards",status:"Placeholder",summary:"Workshop and synthesis artifacts to be added.",detail:pending+" Explain the question explored and the resulting decision."},
  {id:"concepts",title:"Early concepts",status:p.slug==="digital-assistance"||p.slug==="upgather"?"Artifact available":"Placeholder",summary:p.slug==="digital-assistance"?"Conversational mobile prototype.":p.slug==="upgather"?"Editorial workflow exploration.":"Approved concepts to be added.",detail:p.slug==="digital-assistance"?"The supplied conversational mobile prototype shows one assistance surface. It is a design artifact, not proof of a launch outcome.":p.slug==="upgather"?"The supplied sequence shows an editorial workflow exploration. It does not establish production status or measured effects.":pending,src:p.slug==="digital-assistance"||p.slug==="upgather"?proof.visual:undefined},
  {id:"failed",title:"Failed concepts",status:"Placeholder",summary:"An abandoned direction and what it taught us.",detail:pending+" No failed concept is documented in the current notes. Add the alternative, why it was dropped, and the evidence."},
  {id:"testing",title:"Testing findings",status:"Placeholder",summary:"Specific findings and post-test changes pending.",detail:proof.testing},
  {id:"stakeholders",title:"Stakeholder communication",status:"Project summary",summary:"Contribution and alignment from project notes.",detail:p.contribution.join(". ")+". Add approved workshop notes or a decision record to substantiate stakeholder changes."},
  {id:"product",title:"Product constraints",status:"Project summary",summary:"Context that shaped the experience.",detail:p.challenge},
  {id:"engineering",title:"Engineering constraints",status:"Project summary",summary:"System and implementation considerations.",detail:proof.partners[1].contribution+" "+proof.partners[1].change+" Add an approved decision record for the specific technical constraint and its effect."},
  strategyEvidence(p.slug),
  ...(p.slug==="digital-assistance"?[maturityEvidence]:[])
 ];
}
export function getProof(slug:string):Proof { const project=projects.find(p=>p.slug===slug)!;const proof=base[slug];return {...proof,evidence:evidenceFor(project,proof)}; }
