'use client';
import { useEffect,useRef,useState,type ChangeEvent } from 'react';
import { ArrowUp,ArrowDown,Check,Eye,ImagePlus,Save,X } from 'lucide-react';
import ThemeToggle from './theme-toggle';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';
import { contentSchema,sectionLabels,type PortfolioContent } from '@/lib/portfolio-content';
import type { StoredDocument } from '@/lib/portfolio-store';
import { acceptedMediaTypes,maxMediaBytes } from '@/lib/hero-media';
type Target='home'|string;
async function result<T>(response:Response):Promise<T>{const value=await response.json().catch(()=>({error:'The request could not finish. Try again.'})) as T & {error?:string};if(!response.ok)throw new Error(value.error||'Try again.');return value;}
function Field({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(value:string)=>void;multiline?:boolean}){return <label className="editor-field"><span>{label}</span>{multiline?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={4}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
function Reorder({items,label,onChange}:{items:string[];label:(id:string)=>string;onChange:(ids:string[])=>void}){function move(i:number,d:number){const next=[...items];[next[i],next[i+d]]=[next[i+d],next[i]];onChange(next);}return <ol className="editor-order">{items.map((id,i)=><li key={id}><span className="editor-order-number">{String(i+1).padStart(2,'0')}</span><span>{label(id)}</span><button disabled={i===0} onClick={()=>move(i,-1)} aria-label={`Move ${label(id)} up`}><ArrowUp size={16}/></button><button disabled={i===items.length-1} onClick={()=>move(i,1)} aria-label={`Move ${label(id)} down`}><ArrowDown size={16}/></button></li>)}</ol>;}
const labels:Record<string,string>={title:'Project title',company:'Company',subtitle:'Project summary',role:'Your role',domain:'Focus',challenge:'The challenge',evidence:'Documented contribution',takeaway:'What I take forward',scope:'Scope',collaboration:'Product + Engineering collaboration',visualLabel:'Opening visual caption',researchIntro:'Research introduction',researchNote:'Research context note',outcomeNote:'Outcomes context note',choice:'Decision 01 title',why:'Decision 01 reasoning',directional:'Outcome headline',context:'Strategy introduction',opportunity:'Opportunity to test',name:'Level name',principle:'Principle',stage:'Stage label',summary:'Summary',customer:'Customer experience',product:'Product team focus',engineering:'Engineering team focus',example:'Illustrative question',exampleResponse:'Illustrative response'};
export default function PortfolioEditor(){
 const [content,setContent]=useState<PortfolioContent|null>(null),[saved,setSaved]=useState<StoredDocument|null>(null),[published,setPublished]=useState<StoredDocument|null>(null);
 const [target,setTarget]=useState<Target>('home'),[panel,setPanel]=useState('overview'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false),[reviewed,setReviewed]=useState<number|null>(null),[viewport,setViewport]=useState('desktop');
 const previewFrame=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{const close=(event:MessageEvent)=>{if(event.origin===window.location.origin&&event.source===previewFrame.current?.contentWindow&&event.data?.portfolioPreview==='close')setPreview(false);};window.addEventListener('message',close);return()=>window.removeEventListener('message',close);},[]);
 const dirty=!!content&&!!saved&&JSON.stringify(content)!==JSON.stringify(saved.content);
 const pending=!!content&&!!published&&JSON.stringify(content)!==JSON.stringify(published.content);
 async function load(){setError('');try{const data=await result<{draft:StoredDocument;published:StoredDocument}>(await fetch('/api/portfolio-editor',{cache:'no-store'}));setContent(data.draft.content);setSaved(data.draft);setPublished(data.published);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function update(change:(value:PortfolioContent)=>void){setContent(current=>{if(!current)return current;const next=structuredClone(current);change(next);return next;});setReviewed(null);setMessage('');}
 async function save(){if(!content||!saved)return null;const parsed=contentSchema.safeParse(content);if(!parsed.success){setError(`Please check the text fields before saving. ${parsed.error.issues[0].message}`);return null;}setBusy(true);setError('');try{const data=await result<{draft:StoredDocument}>(await fetch('/api/portfolio-editor',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:parsed.data,revision:saved.revision})}));setContent(data.draft.content);setSaved(data.draft);setMessage('Draft saved. Your live portfolio is unchanged.');return data.draft;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 async function openPreview(){const draft=dirty||!saved?.revision?await save():saved;if(!draft)return;setReviewed(draft.revision);setPreview(true);}
 async function publish(){if(!saved||dirty||reviewed!==saved.revision)return;setBusy(true);setError('');try{const data=await result<{published:StoredDocument}>(await fetch('/api/portfolio-editor/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:saved.revision})}));setPublished(data.published);setMessage('Published. Your portfolio now shows this version.');setReviewed(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file||!content||target==='home')return;if(!acceptedMediaTypes.includes(file.type)||file.size>maxMediaBytes){setError('Use an image or video under 50 MB.');return;}const slug=target;setBusy(true);setError('');try{const media=await result<{src:string;type:'image'|'video'}>(await fetch('/api/portfolio-media',{method:'POST',headers:{'Content-Type':file.type},body:file}));update(d=>{d.studies[slug].media.push({...media,title:file.name.replace(/\.[^.]+$/,''),caption:''});});setMessage('Media uploaded to your draft. Add a title and caption, then save.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const study=content&&target!=='home'?content.studies[target]:null;
 const setStudy=(key:string,value:unknown)=>update(d=>{(d.studies[target] as unknown as Record<string,unknown>)[key]=value;});
 const homeField=(key:keyof PortfolioContent['home'],label:string,multi=false)=>content&&<Field key={key} label={label} value={content.home[key] as string} multiline={multi} onChange={v=>update(d=>{(d.home as unknown as Record<string,unknown>)[key]=v;})}/>;
 const studyField=(key:string,multi=true)=>study&&<Field key={key} label={labels[key]||key} value={(study as unknown as Record<string,string>)[key]} multiline={multi} onChange={v=>setStudy(key,v)}/>;
 const detailField=(key: 'timeframe'|'assessmentDate'|'researchObservation'|'designChange'|'deliveryExample',label:string,multiline=false)=>study&&<Field label={label} value={study.caseDetails?.[key]||''} multiline={multiline} onChange={value=>update(d=>{d.studies[target].caseDetails={...d.studies[target].caseDetails,[key]:value};})}/>;
 const projectField=(key:string,multi=true)=>study&&<Field key={key} label={labels[key]||key} value={(study.project as unknown as Record<string,string>)[key]} multiline={multi} onChange={v=>update(d=>{(d.studies[target].project as unknown as Record<string,unknown>)[key]=v;})}/>;
 const strings=(values:string[],label:string,change:(values:string[])=>void)=><div className="editor-fields">{values.map((value,i)=><Field key={i} label={`${label} ${i+1}`} value={value} multiline onChange={v=>change(values.map((x,n)=>n===i?v:x))}/>)}</div>;
 return <div className="portfolio-editor">
 <header className="editor-header"><a className="editor-brand" href="/">TG <span>Terry Germany</span></a><span className="editor-private">Private editor</span><div className="editor-actions"><ThemeToggle/><button className="editor-button" disabled={busy||!content||!dirty&&!!saved?.revision} onClick={()=>void save()}><Save size={16}/>{busy?'Working…':'Save draft'}</button><button className="editor-button" disabled={busy||!content} onClick={()=>void openPreview()}><Eye size={16}/>Preview</button><button className="editor-button editor-primary" disabled={busy||!pending||dirty||reviewed!==saved?.revision} title={dirty?"Save and preview your changes first":reviewed!==saved?.revision?"Preview your saved draft first":"Publish this saved draft"} onClick={()=>void publish()}>Publish</button></div></header>
 <div className="editor-shell"><aside className="editor-sidebar"><p className="editor-eyebrow">Portfolio</p><button className={target==='home'?'selected':''} onClick={()=>{setTarget('home');setPanel('overview');}}>Homepage</button><p className="editor-eyebrow">Case studies</p>{content?.projectOrder.map(slug=><button key={slug} className={target===slug?'selected':''} onClick={()=>{setTarget(slug);setPanel('overview');}}>{content.studies[slug].project.company}</button>)}<a href="/" className="editor-live-link" target="_blank" rel="noopener noreferrer">View live portfolio</a><p className="editor-help">Save your draft, preview it, then publish when you’re ready.</p></aside>
 <main className="editor-main"><div className="editor-heading"><div><p className="editor-eyebrow">Edit Portfolio</p><h1>{target==='home'?'Homepage':study?.project.company||'Loading…'}</h1></div><span className={`editor-status ${dirty?'unsaved':''}`}>{dirty?'Unsaved changes':pending?'Saved draft':content?'Up to date':'Loading…'}</span></div>
 {error&&<div className="editor-error" role="alert">{error}{!content&&<button onClick={()=>void load()}>Try again</button>}</div>}{message&&<p className="editor-message" role="status"><Check size={16}/>{message}</p>}
 {!content&&!error&&<p role="status">Loading your portfolio…</p>}
 {content&&<fieldset className="editor-workspace" disabled={busy}>
 {target==='home'?<><section className="editor-card"><h2>Hero</h2>{homeField('heroBadge','Role & specialization')}{strings(content.home.heroLines,'Headline line',v=>update(d=>{d.home.heroLines=v;}))}{homeField('heroDescription','Introduction',true)}</section><section className="editor-card"><h2>Selected work</h2>{homeField('workTitle','Section title')}{homeField('workDescription','Section introduction',true)}<h3>Project order</h3><Reorder items={content.projectOrder} label={slug=>content.studies[slug].project.company} onChange={v=>update(d=>{d.projectOrder=v;})}/></section><section className="editor-card"><h2>About</h2>{homeField('aboutTitle','About headline',true)}{strings(content.home.aboutParagraphs,'About paragraph',v=>update(d=>{d.home.aboutParagraphs=v;}))}</section></>:study&&<>
 <nav className="editor-tabs" aria-label="Edit case study">{[['overview','Overview'],['research','Research'],['evidence','Evidence'],['strategy','Strategy'],['decisions','Design'],['impact','Outcomes'],...(target==='digital-assistance'?[['maturity','Maturity']]:[]),['media','Media'],['order','Order']].map(([id,label])=><button key={id} aria-current={panel===id?'page':undefined} className={panel===id?'selected':''} onClick={()=>setPanel(id)}>{label}</button>)}</nav>
 <section className="editor-card"><h2>{panel==='overview'?'Project overview':panel==='media'?'Images & videos':panel==='order'?'Section order':sectionLabels[panel]||'Edit section'}</h2>
 {panel==='overview'&&<>{target==='digital-assistance'&&detailField('timeframe','Project timeframe (optional)')}{['company','title','subtitle','role','domain'].map(k=>projectField(k,k==='subtitle'))}{studyField('scope')}{projectField('challenge')}{strings(study.project.contribution,'Contribution',v=>update(d=>{d.studies[target].project.contribution=v;}))}{studyField('collaboration')}{studyField('visualLabel',false)}</>}
 {panel==='research'&&<>{studyField('researchIntro')}{strings(study.insights,'Research insight',v=>setStudy('insights',v))}{studyField('researchNote')}{target==='digital-assistance'&&<><h3>One real research takeaway</h3><p className="editor-note">Add an observation, the change it prompted, and an image showing the change. This example appears once all three are filled in.</p>{detailField('researchObservation','What we observed',true)}{detailField('designChange','What I changed',true)}<label className="editor-field"><span>Screen showing the change</span><select value={study.caseDetails?.researchArtifactSrc||''} onChange={event=>update(d=>{d.studies[target].caseDetails={...d.studies[target].caseDetails,researchArtifactSrc:event.target.value};})}><option value="">Select an image</option>{[{src:'/work/state-farm-hero-phone.png',title:'Digital Assistant — license scanning'},{src:'/work/state-farm-hero-laptop.png',title:'Returning-customer homepage'},...study.media.filter(item=>item.type==='image')].map(item=><option key={item.src} value={item.src}>{item.title}</option>)}</select></label></>}</>}
 {panel==='evidence'&&<><p className="editor-note">Only published, non-placeholder evidence appears in the case study.</p>{study.evidence.filter(e=>['research','concepts','engineering','ai-maturity','stakeholders'].includes(e.id)).map(e=><details className="editor-detail" key={e.id}><summary>{e.title}</summary><label className="editor-field"><span>Source status</span><select value={e.status} onChange={event=>update(d=>{d.studies[target].evidence.find(x=>x.id===e.id)!.status=event.target.value as typeof e.status;})}>{['Project summary','Artifact available','Placeholder'].map(s=><option key={s}>{s}</option>)}</select></label>{(['title','summary','detail'] as const).map(key=><Field key={key} label={key==='detail'?'Full context':key==='summary'?'Card summary':'Evidence title'} value={e[key]} multiline={key!=='title'} onChange={v=>update(d=>{d.studies[target].evidence.find(x=>x.id===e.id)![key]=v;})}/>)}</details>)}</>}
 {panel==='strategy'&&<>{target==='digital-assistance'&&detailField('assessmentDate','Radar assessment date (optional)')}<Field label="Strategy introduction" value={study.strategy.context} multiline onChange={v=>update(d=>{d.studies[target].strategy.context=v;})}/><h3>Competitive intelligence</h3>{study.strategy.comparisons.map((c,i)=><div className="editor-subcard" key={i}>{(['title','question'] as const).map(key=><Field key={key} label={key==='title'?`Comparison ${i+1}`:'Comparison question'} value={c[key]} multiline={key==='question'} onChange={v=>update(d=>{d.studies[target].strategy.comparisons[i][key]=v;})}/>)}</div>)}<h3>Engagement strategy</h3>{study.strategy.engagement.map((c,i)=><div className="editor-subcard" key={i}>{(['title','direction'] as const).map(key=><Field key={key} label={key==='title'?`Step ${i+1}`:'Direction'} value={c[key]} multiline={key==='direction'} onChange={v=>update(d=>{d.studies[target].strategy.engagement[i][key]=v;})}/>)}</div>)}<Field label="Opportunity to test" value={study.strategy.opportunity} multiline onChange={v=>update(d=>{d.studies[target].strategy.opportunity=v;})}/>{strings(study.strategy.signals,'Proposed measure',v=>update(d=>{d.studies[target].strategy.signals=v;}))}</>}
 {panel==='decisions'&&<>{studyField('choice')}{studyField('why')}<Field label="Decision 02 title" value={study.project.decisions[1].title} onChange={v=>update(d=>{d.studies[target].project.decisions[1].title=v;})}/><Field label="Decision 02 reasoning" value={study.project.decisions[1].text} multiline onChange={v=>update(d=>{d.studies[target].project.decisions[1].text=v;})}/></>}
 {panel==='impact'&&<>{target==='digital-assistance'&&detailField('deliveryExample','A pattern or standard the team adopted—and how it was used',true)}{studyField('directional')}{projectField('evidence')}{studyField('outcomeNote')}{projectField('takeaway')}</>}
 {panel==='maturity'&&<><Field label="Your maturity-model contribution" value={content.maturity.contribution} multiline onChange={v=>update(d=>{d.maturity.contribution=v;})}/>{content.maturity.levels.map((l,i)=><details className="editor-detail" key={l.level}><summary>Level {l.level} · {l.name}</summary>{(['name','principle','stage','summary','customer','product','engineering','example','exampleResponse'] as const).map(key=><Field key={key} label={labels[key]} value={l[key]} multiline={!['name','principle','stage'].includes(key)} onChange={v=>update(d=>{d.maturity.levels[i][key]=v;})}/>)}{strings(l.capabilities,'Capability',v=>update(d=>{d.maturity.levels[i].capabilities=v;}))}</details>)}</>}
 {panel==='order'&&<><p className="editor-note">{target==='digital-assistance'?'Overview stays first. Evidence cards are included in Research.':'Overview stays first. Use the controls to arrange the remaining sections.'}</p><Reorder items={target==='digital-assistance'?study.sectionOrder.filter(id=>id!=='evidence'):study.sectionOrder} label={id=>sectionLabels[id]} onChange={v=>setStudy('sectionOrder',target==='digital-assistance'?['evidence',...v]:v)}/></>}
 {panel==='media'&&<><p className="editor-note">Media appears in Design decisions. Uploads stay in the draft until you publish.</p><label className="editor-button editor-upload"><ImagePlus size={18}/>Upload image or video<input type="file" accept={acceptedMediaTypes.join(',')} disabled={busy||study.media.length>=12} onChange={e=>void upload(e)} aria-label="Upload case-study media"/></label><p className="editor-note">JPG, PNG, WebP, AVIF, MP4, WebM · Up to 50 MB · 12 items per project</p>{study.media.length===0&&<div className="editor-empty">Add your first case-study image or walkthrough.</div>}{study.media.map((m,i)=><div className="editor-media-card" key={m.src}>{m.type==='video'?<video controls preload="metadata" src={m.src}/>:<img src={m.src} alt={m.title}/>}<div><Field label={`Media ${i+1} title / image description`} value={m.title} onChange={v=>update(d=>{d.studies[target].media[i].title=v;})}/><Field label="Caption" value={m.caption} multiline onChange={v=>update(d=>{d.studies[target].media[i].caption=v;})}/><div className="editor-media-actions"><button disabled={i===0} onClick={()=>update(d=>{const list=d.studies[target].media;[list[i],list[i-1]]=[list[i-1],list[i]];})} aria-label={`Move media ${i+1} up`}><ArrowUp size={16}/></button><button disabled={i===study.media.length-1} onClick={()=>update(d=>{const list=d.studies[target].media;[list[i],list[i+1]]=[list[i+1],list[i]];})} aria-label={`Move media ${i+1} down`}><ArrowDown size={16}/></button><button onClick={()=>update(d=>{d.studies[target].media.splice(i,1);})}>Remove from draft</button></div></div></div>)}</>}
 </section></>}
 </fieldset>}
 {content&&<p className="editor-save-time">{saved?.updatedAt?`Draft saved ${new Date(saved.updatedAt).toLocaleString()}`:'Your existing portfolio is the starting point.'} {reviewed===saved?.revision&&!dirty?'Preview reviewed. Ready to publish.':'Preview your saved draft to enable publishing.'}</p>}
 </main></div>
 <Dialog open={preview} onOpenChange={setPreview}><DialogContent fullScreen showCloseButton={false} className="editor-preview-overlay"><DialogTitle className="sr-only">Draft preview</DialogTitle><DialogDescription className="sr-only">Review your saved draft before publishing. Escape returns to the editor.</DialogDescription><header><div><strong>Draft preview</strong><span>Changes are not live</span></div><div className="editor-preview-controls"><label>Device <select aria-label="Preview device" value={viewport} onChange={e=>setViewport(e.target.value)}><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select></label><button autoFocus className="editor-button" onClick={()=>setPreview(false)}><X size={17}/>Back to editor</button></div></header><div className="editor-preview-stage"><iframe ref={previewFrame} key={`${target}-${saved?.revision}`} className={viewport==='mobile'?'mobile':''} src={`/edit/preview${target==='home'?'':`?project=${target}`}`} title={`${target==='home'?'Homepage':study?.project.company} draft preview`}/></div></DialogContent></Dialog>
 </div>;
}
