export const focusAreas = ["AI", "Leadership", "Research", "Design Systems", "Enterprise", "Hands-on Craft"] as const;
export type Focus = (typeof focusAreas)[number];
export const roles = ["Hiring Manager", "Executive", "Designer", "Engineer"] as const;
export type VisitorRole = (typeof roles)[number];
export type Project = { slug:string; company:string; title:string; subtitle:string; role:string; tags:Focus[]; color:string; domain:string; challenge:string; approach:string; decisions:{title:string;text:string}[]; contribution:string[]; evidence:string; takeaway:string; };
export const projects:Project[] = [
 {"slug":"digital-assistance","company":"State Farm","title":"Making complex insurance feel human.","subtitle":"B2C Digital Assistant + AI: experience strategy, research, and product design across insurance journeys.","role":"Senior Experience Lead · AI & Digital Assistance","domain":"B2C AI experience strategy","challenge":"Insurance journeys and emerging AI initiatives were spread across separate teams, forms, and digital surfaces. I defined an assistance model around customer intent: understand the goal, guide complex decisions, explain recommendations, and connect people to human support when needed.","contribution":["Led 25+ specialists across Design, Research, Data Science, Engineering, Product, Content, and AI.","Owned strategy across 12+ journeys: SmartQuote, quote review/purchase, service, registration/onboarding, claims/FNOL, and policy/vehicle management.","Directed research, prototypes, experimentation, and the Digital Assistance Design Kit; implemented the Level 1–3 AI Maturity Model with Product and Engineering."],"evidence":"Established shared AI experience principles, reusable interaction patterns, and experience governance across State Farm’s consumer ecosystem. Connected near-term product work with a longer-term roadmap for generative AI, predictive assistance, and emerging agentic experiences.","takeaway":"AI should help people accomplish a goal while making its behavior understandable. Trust, accessibility, transparency, and human support belong in the interaction model from the start.","decisions":[{"title":"Match assistance to the customer’s task.","text":"Designed full-page AI, widgets, side panels, embedded assistance, and mobile experiences, with transitions between conversational and traditional interfaces."},{"title":"Give AI a shared interaction foundation.","text":"Built and governed the Digital Assistance Design Kit: prompt and input behavior, quick replies, AI-generated cards, explainability, human handoff, error recovery, trust, and responsive desktop/mobile patterns."},{"title":"Test discovery, usefulness, and trust.","text":"Evaluated AI entry points, CTA language, suggestion chips, proactive assistance, visual treatments, AI identity, and human escalation through research and experimentation."}],"tags":["AI","Leadership","Research","Enterprise"],"color":"coral","approach":"Led B2C AI experience strategy, research, interaction architecture, prototyping, and governance across 12+ insurance journeys. Built the Digital Assistance Design Kit and aligned a multidisciplinary team around customer intent, trust, and scalable delivery."},
 { slug:"apple-intelligence", company:"Apple", title:"Intelligence that belongs in the experience.", subtitle:"Interaction patterns, research, and systems thinking across intelligent product surfaces.", role:"Senior Product Designer · Apple Intelligence (contract)", tags:["AI","Research","Design Systems","Hands-on Craft"], color:"violet", domain:"Intelligent ecosystems", challenge:"Intelligent capabilities need to fit familiar product behavior while remaining understandable, accessible, and consistent across platforms.", approach:"Partnered with data scientists, ML engineers, and platform teams on Apple Intelligence UI and UX across iOS, macOS, tvOS, and web. Combined UX research, experience architecture, interaction design, and prototype validation.", decisions:[{title:"Start with the interaction",text:"Translated intelligent system behavior into product flows and patterns aligned with Apple's Human Interface Guidelines and accessibility principles."},{title:"Build a common foundation",text:"Supported the shift from Sketch to Figma through unified systems, reusable components, and cross-team workflows."},{title:"Validate before scaling",text:"Used usability testing and prototype iteration to refine interaction quality and shared design standards."}], contribution:["UI/UX for Apple Intelligence product surfaces","Research, strategy, and experience architecture","Sketch-to-Figma migration and component systems","Designer mentorship and prototype validation"], evidence:"A high-level account of role and approach. Proprietary screens, internal research, and implementation details are not reproduced here.", takeaway:"The most useful intelligence feels coherent with the product around it." },
 { slug:"upgather", company:"Scoop News Group / Upgather", title:"Clarity for people running complex work.", subtitle:"Enterprise platform design spanning event operations, analytical data, and connected workflows.", role:"Principal Product Designer · AI & Government SaaS", tags:["Enterprise","Design Systems","Hands-on Craft","Leadership"], color:"mint", domain:"Enterprise product design", challenge:"Event and data workflows span speakers, organizations, invitations, content, and publishing. People need to see their next step without understanding the underlying system.", approach:"Defined a North Star experience while designing platform flows. Simplified event-page creation and reusable layouts, organized operational tables and contextual panels, and aligned the design system with engineering.", decisions:[{title:"Give creation a clear start",text:"Separated guided event setup from ongoing management: choose a new layout, reuse an existing layout, or save a draft before returning to the operational workspace."},{title:"Make complexity navigable",text:"Used AG Grid and contextual panels for operational work, with consistent draft states and deliberate minimize behavior."},{title:"Close the design-to-code gap",text:"Worked with engineering on consistency and change tracking across Figma, Storybook, and the repository. Automation remains an evolving workflow."}], contribution:["Cross-product direction and hands-on design","Event-page creator and operational workflows","Members, organizations, invitations, and confirmations","Design-system alignment with engineering"], evidence:"The event-creator and system-alignment work are ongoing design initiatives. Integration concepts and automation plans are distinguished from completed production capabilities.", takeaway:"A strong enterprise experience makes the next decision obvious, even when the system underneath is complex." },
 { slug:"design-systems", company:"Across products", title:"Shared language. Better delivery.", subtitle:"Systems connecting interaction decisions, reusable components, and implementation.", role:"Design systems & engineering partnership", tags:["Design Systems","Enterprise","Leadership","Hands-on Craft"], color:"blue", domain:"Systems + scale", challenge:"A library becomes useful when designers and engineers understand the same component behavior, variation, and constraints.", approach:"Built and evolved Figma systems, linked design intent to engineering patterns, and used prototypes and working sessions to make constraints visible early. Established repeatable standards with room for product-specific decisions.", decisions:[{title:"Define behavior",text:"Documented states, accessibility, content, responsive behavior, and handoff expectations alongside visual components."},{title:"Engineer alongside design",text:"Worked through implementation trade-offs and prototype reviews, using Storybook and repository workflows as shared references."},{title:"Make changes traceable",text:"Explored a Figma-to-repository change process with documented changes and tracked work before advancing toward automation."}], contribution:["Reusable Figma components and interaction patterns","Design standards and implementation alignment","Designer mentoring and cross-team collaboration","Structured handoff and change tracking"], evidence:"This cross-project overview describes methods and contributions. It does not imply that Figma MCP automatically synchronizes systems or that proposed automation is deployed.", takeaway:"Design ahead. Engineer alongside. Build together." },
];
export const roleCopy:Record<VisitorRole,{headline:string;text:string;tags:Focus[]}> = {
 "Hiring Manager":{headline:"The experience. The craft. The impact.",text:"Start with AI strategy, cross-team leadership, and the hands-on work behind it.",tags:["AI","Leadership"]},
 Executive:{headline:"From direction to shared execution.",text:"Explore how customer problems become a connected vision, priorities, and a path for teams to deliver.",tags:["Leadership","Enterprise"]},
 Designer:{headline:"Follow the decisions behind the design.",text:"Explore research, interaction patterns, prototypes, and the systems that make an experience coherent.",tags:["Research","Hands-on Craft"]},
 Engineer:{headline:"See how design meets implementation.",text:"Start with reusable systems, technical constraints, and collaboration from prototype through delivery.",tags:["Design Systems","Enterprise"]},
};
export function rankProjects(tags:readonly Focus[]):Project[] { return [...projects].sort((a,b)=>b.tags.filter(t=>tags.includes(t)).length-a.tags.filter(t=>tags.includes(t)).length); }
export function answerQuestion(question:string,role:VisitorRole) {
 const q=question.toLowerCase();
 if(/research|test|insight|validation/.test(q)) return {title:"Research that changes the direction.",text:"Terry connects usability testing, experimentation, and prototype validation to product decisions. Explore the insurance entry-point and interface studies, or research-to-interaction work around Apple Intelligence.",projects:rankProjects(["Research"]).slice(0,2)};
 if(/engineer|implementation|storybook|figma|system|mcp|code/.test(q)) return {title:"A shared system from design to delivery.",text:"Terry partners with engineering on component behavior, technical constraints, prototypes, and traceable changes. Automated Figma-to-repository syncing is a proposed workflow, not an established production capability.",projects:[projects[3],projects[2]]};
 if(/lead|mentor|team|strategy|executive/.test(q)) return {title:"Vision with a path to execution.",text:"Terry combines hands-on design with cross-team direction and mentorship. At State Farm, the scope includes 12+ journeys and influence across 15+ teams. At Scoop News Group, he connects a North Star experience to practical enterprise product work.",projects:[projects[0],projects[2]]};
 if(/craft|prototype|hands|build|interaction/.test(q)) return {title:"Strategy you can see and interact with.",text:"Executive prototypes, conversation patterns, reusable components, and operational workflows are central to Terry's practice. Explore interaction decisions around Apple Intelligence and the event-page creator at Upgather.",projects:[projects[1],projects[2]]};
 if(/\bai\b|trust|agent|conversation|background|experience|work|terry|insurance/.test(q)) return {title:"Human insight, expressed through intelligent systems.",text:"Terry designs the relationship between people and intelligent products: clear interaction, useful guidance, explainability, and a path to human help. State Farm and Apple Intelligence are the strongest starting points.",projects:[projects[0],projects[1]]};
 return {title:"That detail isn't in the portfolio yet.",text:"This guide searches curated portfolio topics. Try AI experiences, research, leadership, or engineering collaboration, or explore the projects recommended for your view.",projects:rankProjects(roleCopy[role].tags).slice(0,2)};
}
export const principles = [
 {title:"Understand the human context.",text:"Start with the decision someone needs to make, the uncertainty they face, and the outcome that matters.",project:"digital-assistance"},
 {title:"Make intelligence understandable.",text:"Define what the system can do, how it communicates, and where the person remains in control.",project:"apple-intelligence"},
 {title:"Connect the whole system.",text:"Bring product, design, research, and engineering into the same conversation early.",project:"design-systems"},
 {title:"Prototype. Learn. Refine.",text:"Make the idea tangible, test the important assumptions, and let evidence shape the next version.",project:"upgather"},
];
